### PR TITLE
chore(deps): Update dependencies

### PR DESCRIPTION
**Pull request by martinalbert**
`npm-check-updates` output:
```
 @popperjs/core      ^2.10.2  →  ^2.11.6
 acorn                ^8.0.0  →   ^8.8.2
 bootstrap            ^5.1.3  →   ^5.2.3
 buttercms            ^1.2.8  →   ^1.2.9
 camelcase-keys       ^7.0.1  →   ^8.0.2
 date-fns            ^2.25.0  →  ^2.29.3
 eslint              ^8.12.0  →  ^8.32.0
 eslint-config-next  ^12.1.4  →  ^13.1.5
 next                ^12.1.0  →  ^13.1.5
 react               ^17.0.2  →  ^18.2.0
 react-dom           ^17.0.2  →  ^18.2.0
 sharp               ^0.29.3  →  ^0.31.3
 typescript           ^3.3.1  →   ^4.9.4
```
### Major changes
- `camelcase-keys` - requires Node ≥ 14 ([link](https://github.com/sindresorhus/camelcase-keys/releases/tag/v8.0.0))
- `next` and `eslint-config-next`
  - [all changes in v13](https://github.com/vercel/next.js/releases/tag/v13.0.0)
  - more helpful links: 
    - [overview of changes](https://nextjs.org/blog/next-13)
    - [breaking changes](https://nextjs.org/blog/next-13#breaking-changes) - this involves: 
      - change regarding next/link which throws error in dev mode
      - minimum react version bumped to v18.2.0
- `react` & `react-dom`
  - [v18 changes](https://github.com/facebook/react/releases/tag/v18.0.0) (ReactDom.render() deprecated and more)
  - [overview of changes](https://reactjs.org/blog/2022/03/29/react-v18.html)
- `typescript`
  - [v4 changes](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/) ([breaking changes](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#breaking-changes))

### `npm audit`
- on main branch found 4 vulnerabilities (1 moderate, 2 high, 1 critical)
- after npm audit fix found 1 moderate severity vulnerability
- after update of dependencies listed above found 0 vulnerabilities

### Implications
after `next` upgrade to v13, there are problems with running next in dev mode, but it doesn’t throw any errors when using `npm run build; npm run start`:
```
Invalid <Link> with <a> child. Please remove <a> or use <Link legacyBehavior>.
Learn more: <https://nextjs.org/docs/messages/invalid-new-link-with-extra-anchor>
```

### CODE REVIEW

**Comment by ViolanteCodes** [comment]
@martinalbert i attempted to install this with node 16.14.0 and I'm getting an error that only 14.1 is supported:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: undefined,
npm WARN EBADENGINE   required: { node: '14.17.1' },
npm WARN EBADENGINE   current: { node: 'v16.14.0', npm: '8.3.1' }
npm WARN EBADENGINE }
```

This didn't use to happen before, though?

**Comment by martinalbert** [comment]
@ViolanteCodes there is set version of node in [package.json engines](https://github.com/ButterCMS/nextjs-starter-buttercms/blob/6ed4ba9dafa2a70331d4ba3d1299ce00e8f65118/package.json#L28-L30) to `14.17.1`. Seems to be working on newer versions, but maybe it's intentional.

**Comment by ViolanteCodes** [comment]
> @ViolanteCodes there is set version of node in [package.json engines](https://github.com/ButterCMS/nextjs-starter-buttercms/blob/6ed4ba9dafa2a70331d4ba3d1299ce00e8f65118/package.json#L28-L30) to `14.17.1`. Seems to be working on newer versions, but maybe it's intentional.

@martinalbert can we remove for now and see if it works?

**Comment by martinalbert** [comment]
@ViolanteCodes major versions of node lower than v14 doesn't work, so what about modifying it to `>=14.17.1`?

**Comment by ViolanteCodes** [comment]
> @ViolanteCodes major versions of node lower than v14 doesn't work, so what about modifying it to `>=14.17.1`?

@martinalbert that works for me

**Review by ViolanteCodes — CHANGES_REQUESTED** [review]
This doesn't seem to be working for localhost?

I did a clean download, checkout PR, nvm into node 16.14.0, npm install, npm run dev, and added token.

I get the following error in terminal:

```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /home/maria/Programming/butter/starters/nextjs-starter-buttercms/.env
event - compiled client and server successfully in 792 ms (333 modules)
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 318 ms (334 modules)
warn  - Fast Refresh had to perform a full reload due to a runtime error.
wait  - compiling /landing-page/[slug] (client and server)...
event - compiled client and server successfully in 727 ms (420 modules)
Image with src "https://cdn.buttercms.com/hWC1eXQLyYZKE4h03CLQ" has legacy prop "layout". Did you forget to run the codemod?
Read more: https://nextjs.org/docs/messages/next-image-upgrade-to-13
Image with src "https://cdn.buttercms.com/hWC1eXQLyYZKE4h03CLQ" has legacy prop "objectFit". Did you forget to run the codemod?
Read more: https://nextjs.org/docs/messages/next-image-upgrade-to-13
Image with src "https://cdn.buttercms.com/zwL5xPiR8yFbSYYG6kgr" has legacy prop "layout". Did you forget to run the codemod?
Read more: https://nextjs.org/docs/messages/next-image-upgrade-to-13
Image with src "https://cdn.buttercms.com/zwL5xPiR8yFbSYYG6kgr" has legacy prop "objectFit". Did you forget to run the codemod?
Read more: https://nextjs.org/docs/messages/next-image-upgrade-to-13
Image with src "https://cdn.buttercms.com/UrvV7047TridMZx0RpOc" has legacy prop "layout". Did you forget to run the codemod?
Read more: https://nextjs.org/docs/messages/next-image-upgrade-to-13
Image with src "https://cdn.buttercms.com/UrvV7047TridMZx0RpOc" has legacy prop "objectFit". Did you forget to run the codemod?
Read more: https://nextjs.org/docs/messages/next-image-upgrade-to-13
Image with src "https://cdn.buttercms.com/epLAKeLUSv6xJekCA3NT" has legacy prop "layout". Did you forget to run the codemod?
Read more: https://nextjs.org/docs/messages/next-image-upgrade-to-13
Image with src "https://cdn.buttercms.com/epLAKeLUSv6xJekCA3NT" has legacy prop "objectFit". Did you forget to run the codemod?
Read more: https://nextjs.org/docs/messages/next-image-upgrade-to-13
Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.
    at Lazy
    at Suspense
    at LoadableComponent (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/next/dist/shared/lib/loadable.js:85:9)
    at LandingPageSection (webpack-internal:///./components/landing-page-sections/landing-page-section.js:20:31)
    at LandingPage (webpack-internal:///./pages/landing-page/[slug].js:32:24)
    at MyApp (webpack-internal:///./pages/_app.js:43:18)
    at StyleRegistry (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/styled-jsx/dist/index/index.js:449:36)
    at PathnameContextProviderAdapter (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/next/dist/shared/lib/router/adapters.js:60:11)
    at AppContainer (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/next/dist/server/render.js:290:29)
    at AppContainerWithIsomorphicFiberStructure (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/next/dist/server/render.js:326:57)
    at div
    at Body (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/next/dist/server/render.js:613:21)
error - node_modules/next/dist/client/link.js (269:22) @ LinkComponent
error - Error: Invalid <Link> with <a> child. Please remove <a> or use <Link legacyBehavior>.
Learn more: https://nextjs.org/docs/messages/invalid-new-link-with-extra-anchor
    at LinkComponent (webpack-internal:///./node_modules/next/dist/client/link.js:264:23)
    at renderWithHooks (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderForwardRef (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5842:18)
    at renderElement (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6005:11)
    at renderNodeDestructiveImpl (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7) {
  page: '/landing-page/[slug]'
}
null
```
and this is browser:

```

 1 of 1 unhandled error
Server Error
Error: Invalid <Link> with <a> child. Please remove <a> or use <Link legacyBehavior>.
Learn more: https://nextjs.org/docs/messages/invalid-new-link-with-extra-anchor

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
LinkComponent
node_modules/next/dist/client/link.js (269:22)
renderWithHooks
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5658:16)
renderForwardRef
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5842:18)
renderElement
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6005:11)
renderNodeDestructiveImpl
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6104:11)
renderNodeDestructive
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderNode
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6259:12)
renderHostElement
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5642:3)
renderElement
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5952:5)
renderNodeDestructiveImpl
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6104:11)
renderNodeDestructive
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderNode
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6259:12)
renderChildrenArray
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6211:7)
renderNodeDestructiveImpl
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6141:7)
renderNodeDestructive
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderNode
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6259:12)
renderHostElement
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5642:3)
renderElement
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5952:5)
renderNodeDestructiveImpl
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6104:11)
renderNodeDestructive
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderNode
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6259:12)
renderHostElement
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5642:3)
renderElement
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5952:5)
renderNodeDestructiveImpl
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6104:11)
renderNodeDestructive
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderNode
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6259:12)
renderHostElement
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5642:3)
renderElement
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5952:5)
renderNodeDestructiveImpl
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6104:11)
renderNodeDestructive
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderNode
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6259:12)
renderChildrenArray
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6211:7)
renderNodeDestructiveImpl
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6141:7)
renderNodeDestructive
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderNode
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6259:12)
renderHostElement
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5642:3)
renderElement
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5952:5)
renderNodeDestructiveImpl
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6104:11)
renderNodeDestructive
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderNode
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6259:12)
renderHostElement
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5642:3)
renderElement
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5952:5)
renderNodeDestructiveImpl
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6104:11)
renderNodeDestructive
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderIndeterminateComponent
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5785:7)
renderElement
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5946:7)
renderNodeDestructiveImpl
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6104:11)
renderNodeDestructive
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderNode
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6259:12)
renderChildrenArray
file:///home/maria/Programming/butter/starters/nextjs-starter-buttercms/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6211:7)

```

**Review by ViolanteCodes — APPROVED** [review]
This LGTM. I was able to run locally from a fresh install

**Pull request merged**
