### PR TITLE
Fixed blown cta image on large screen sizes

### PR DESCRIPTION
**Pull request by orlyohreally**
Made the changes from this PR https://github.com/ButterCMS/starter-project-front-end/commit/dd4ba45fc5883ffce4c389f3236b8c2d2a5dd4f2 to fix blown cta image on large screen sizes

### CODE REVIEW

**Comment by ViolanteCodes** [comment]
@orlyohreally 

The blown image is fixed, but something is wrong with the flex layout for the tags + blog posts: [screenshot](https://share.getcloudapp.com/6quEn7N8) vs here is a a similar layout on the django preview app: https://django-starter-buttercms-demo.herokuapp.com/blog/third-sample-post-with-featured/

I'm seeing this issue on both the blog list views and the blog detail views, but it doesn't appear to be happening on the gatsby app [screenshot](https://gatsbyjs-starter-buttercms-vercel-bgii845hy-buttercms.vercel.app/blog), so I'm wondering if something got tweaked in either the css or the template layout itself?

What do you think?

**Comment by orlyohreally** [comment]
@ViolanteCodes The gatsby and django apps seem to have different date formats. Could it be the issue?

**Comment by ViolanteCodes** [comment]
> @ViolanteCodes The gatsby and django apps seem to have different date formats. Could it be the issue?

@orlyohreally 
I think that the nextjs starter is missing some of the css from the starter-project-front-end repo, maybe - it looks like the classes .single-blog-post-meta-info and .blog-roll-card-meta-info in the nextjs starter have a display value of "flex" [screenshot](https://share.getcloudapp.com/NQuxXbEO), but in the front end repo + the django starter, the display value is "inline-block".

[screenshot of starter-project-front-end](https://share.getcloudapp.com/2NuvDx2j)
[screenshot of gastby (same as django)](https://share.getcloudapp.com/6quEnkLg)

I ran the main.css files from the front end repo and the nextjs project in a diff checker and there are a lot of differences - i think maybe because of image handling; you'd mentioned something about how we had to do things differently for nextjs because of how it handles images, if I'm not mistaken, so I'm not sure we can just copy the main.css file from the starter-project-front-end repo into here. What do you think about just updating the one class? I can do this if you think it's a good idea.

**Comment by orlyohreally** [comment]
> 

Let me do a quick look at the diff

**Comment by orlyohreally** [comment]
@ViolanteCodes 
The differences:
https://share.getcloudapp.com/nOu9OY1m
https://share.getcloudapp.com/ApuxdyKG
https://share.getcloudapp.com/qGurGzj1
https://share.getcloudapp.com/NQuxXeRL

I'll check which are changes specifically for Nextjs app (I've already removed the ones that I'm sure are only for this app) and will make changes to this PR

**Comment by ViolanteCodes** [comment]
@orlyohreally is this ready for re-review? Just checking since i forget where we left it

**Comment by ViolanteCodes** [comment]
@orlyohreally This all looks pretty good - one quick question: it is possible to get nextjs to render some more space in between each tag link? they look a bit squished together, but I didn't know how had of a change this would be: https://share.getcloudapp.com/GGuEjGog

**Comment by orlyohreally** [comment]
@ViolanteCodes it seems that that part of the card is created differently https://share.getcloudapp.com/qGurG2Yp

**Comment by orlyohreally** [comment]
@ViolanteCodes I've committed the change

**Comment by orlyohreally** [comment]
@ViolanteCodes I've created a PR for the gatsby project https://github.com/ButterCMS/gatsbyjs-starter-buttercms/pull/48

**Review by ViolanteCodes — COMMENTED** [review]
LGTM

**Pull request merged**
